In [4]:
# 1- create a new column in the orders dataframe with name profit_flag. Set its value as 1 if profit is greater than 0 else set 0.
import pandas as pd
df = pd.read_csv('orders.txt')
df.loc[df['profit'] > 0, 'profit_flag'] = 1
df.loc[df['profit'] <= 0, 'profit_flag'] = 0
df

,order_id,order_date,customer_name,city,category,product_id,sales,profit,profit_flag
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113,1.0
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354,0.0
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696,1.0
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257,1.0
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288,1.0
...,...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696,1.0
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896,1.0
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812,1.0
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640,1.0
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492,0.0

In [10]:
# 2- in the orders data frame rename column names to upper case ..eg order_id should be ORDER_ID
import pandas as pd
df = pd.read_csv('orders.txt')
df.columns = df.columns.str.upper()
df

,ORDER_ID,ORDER_DATE,CUSTOMER_NAME,CITY,CATEGORY,PRODUCT_ID,SALES,PROFIT
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288
...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492

In [12]:
# 3- again change the column names back to lower case
import pandas as pd
df = pd.read_csv('orders.txt')
df.columns = df.columns.str.upper()
df
df.columns = df.columns.str.lower()
df

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288
...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492

In [15]:
# 4- sort the dataframe column by profit in descending order 
import pandas as pd
df = pd.read_csv('orders.txt')
df.sort_values(by = 'profit', ascending = False, inplace=True)
df

,order_id,order_date,customer_name,city,category,product_id,sales,profit
4126,CA-2021-166709,2021-11-17,Hunter Lopez,Newark,Technology,TEC-CO-10004722,10499.970,5039.9856
1968,CA-2020-117121,2020-12-17,Adrian Barton,Detroit,Office Supplies,OFF-BI-10000545,9892.740,4946.3700
547,CA-2018-145541,2018-12-14,Tom Boeckenhauer,New York City,Technology,TEC-MA-10001127,6999.960,2239.9872
3521,CA-2021-135909,2021-10-13,Jane Waco,Sacramento,Office Supplies,OFF-BI-10003527,5083.960,1906.4850
4730,US-2021-102183,2021-08-21,Pete Kriz,New York City,Office Supplies,OFF-BI-10001359,4305.552,1453.1238
...,...,...,...,...,...,...,...,...
1329,CA-2019-140025,2019-04-07,Peter Fuller,San Antonio,Office Supplies,OFF-AP-10002651,463.248,-1181.2824
4821,US-2021-120390,2021-10-19,Tracy Hopkins,Burlington,Office Supplies,OFF-BI-10004995,1633.188,-1306.5504
4458,US-2019-150630,2019-09-17,Tracy Blumstein,Philadelphia,Furniture,FUR-BO-10004834,3083.430,-1665.0522
1020,CA-2019-116638,2019-01-28,Joseph Holt,Concord,Furniture,FUR-TA-10000198,4297.644,-1862.3124
4829,US-2021-122714,2021-12-07,Henry Goldwyn,Chicago,Office Supplies,OFF-BI-10001120,1889.990,-2929.4845

In [19]:
# 5- sort the dataframe column by sales in ascending order , in case of a tie it should be sorted by profit in descending order 
import pandas as pd
df = pd.read_csv('orders.txt')
df.sort_values(by = ['sales', 'profit'], ascending = [True, False], inplace=True)
df

,order_id,order_date,customer_name,city,category,product_id,sales,profit
4731,US-2021-102288,2021-06-19,Zuschuss Carroll,Houston,Office Supplies,OFF-AP-10002906,0.444,-1.1100
3293,CA-2021-124114,2021-03-02,Roland Schwarz,Waco,Office Supplies,OFF-BI-10004022,0.556,-0.9452
2771,CA-2020-168361,2020-06-21,Ken Brennan,Chicago,Office Supplies,OFF-BI-10003727,0.836,-1.3376
162,CA-2018-112403,2018-03-31,Jas O'Carroll,Philadelphia,Office Supplies,OFF-BI-10003529,0.852,-0.5964
4315,US-2018-152723,2018-09-26,Henry Goldwyn,Mesquite,Office Supplies,OFF-BI-10003460,0.876,-1.4016
...,...,...,...,...,...,...,...,...
540,CA-2018-144624,2018-11-19,John Murray,Jamestown,Technology,TEC-PH-10002885,4548.810,1228.1787
3521,CA-2021-135909,2021-10-13,Jane Waco,Sacramento,Office Supplies,OFF-BI-10003527,5083.960,1906.4850
547,CA-2018-145541,2018-12-14,Tom Boeckenhauer,New York City,Technology,TEC-MA-10001127,6999.960,2239.9872
1968,CA-2020-117121,2020-12-17,Adrian Barton,Detroit,Office Supplies,OFF-BI-10000545,9892.740,4946.3700
4126,CA-2021-166709,2021-11-17,Hunter Lopez,Newark,Technology,TEC-CO-10004722,10499.970,5039.9856

In [22]:
# 6- reset the index to original state
df.sort_index(inplace=True)
df

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288
...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492

In [30]:
# 7- create a column as profit_category . sets it value as below:
# if profit < 0 then 'loss'
# if profit between 0 and 100 then 'low profit' 
# if profit between 100 and 500 then 'medium profit'
# else high profit 

# option 1 using df.loc
# df.loc[df['profit'] < 0, 'profit_category'] = 'loss'
# df.loc[df['profit'] == 0, 'profit_category'] = 'no profit no loss'
# df.loc[(df['profit'] > 0) & (df['profit'] <= 100), 'profit_category'] = 'low profit'
# df.loc[(df['profit'] > 100) & (df['profit'] <= 500) ,'profit_category'] = 'medium profit'
# df.loc[df['profit'] > 500, 'profit_category'] = 'high profit'
#df

# option 2 use apply func
def set_profit_category(profit):
    if profit < 0:
        return 'loss'
    elif profit == 0:
        return 'no profit no loss'
    elif profit <= 100:
        return 'low profit'
    elif profit <= 500:
        return 'medium profit'
    elif profit > 500:
        return 'high profit'

df['profit_category'] = df['profit'].apply(set_profit_category)
df

,order_id,order_date,customer_name,city,category,product_id,sales,profit,profit_category
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113,medium profit
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354,loss
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696,low profit
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257,low profit
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288,low profit
...,...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696,low profit
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896,low profit
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812,low profit
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640,low profit
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492,loss

In [32]:
# 8- create a new column sales_profit_ratio and set its value as (profit/sales)*100
df['sales_profit_ratio'] = (df['profit']/df['sales'])*100
df

,order_id,order_date,customer_name,city,category,product_id,sales,profit,profit_category,sales_profit_ratio
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113,medium profit,29.00
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354,loss,-17.50
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696,low profit,35.00
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257,low profit,33.75
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288,low profit,35.00
...,...,...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696,low profit,32.50
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896,low profit,47.00
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812,low profit,47.00
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640,low profit,29.00
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492,loss,-52.00

In [34]:
# 9- find all the orders where customer name starts with 'D' and ends with 'e'
df[(df['customer_name'].str.startswith('D')) & (df['customer_name'].str.endswith('e'))]

,order_id,order_date,customer_name,city,category,product_id,sales,profit,profit_category,sales_profit_ratio
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113,medium profit,29.000000
94,CA-2018-107139,2018-07-05,Dennis Pardue,Los Angeles,Office Supplies,OFF-BI-10001670,180.960,67.8600,low profit,37.500000
159,CA-2018-112158,2018-12-02,David Philippe,New York City,Furniture,FUR-BO-10003272,883.920,-110.4900,loss,-12.500000
169,CA-2018-113271,2018-07-09,Darrin Sayre,San Francisco,Furniture,FUR-BO-10004218,119.833,7.0490,low profit,5.882353
244,CA-2018-120432,2018-08-24,Dorothy Wardle,Owensboro,Office Supplies,OFF-SU-10004661,25.500,6.6300,low profit,26.000000
415,CA-2018-133424,2018-03-30,Dorris liebe,Seattle,Office Supplies,OFF-LA-10002312,44.400,22.2000,low profit,50.000000
433,CA-2018-134621,2018-12-21,Dennis Pardue,Columbia,Office Supplies,OFF-BI-10000977,18.240,-14.5920,loss,-80.000000
626,CA-2018-153150,2018-07-01,Dorris liebe,Seattle,Office Supplies,OFF-BI-10003355,19.920,6.9720,low profit,35.000000
790,CA-2018-168592,2018-09-08,Dennis Pardue,San Francisco,Office Supplies,OFF-AP-10004785,56.650,24.3595,low profit,43.000000
974,CA-2019-112522,2019-10-10,David Philippe,Chicago,Office Supplies,OFF-AR-10003183,8.016,1.0020,low profit,12.500000
1035,CA-2019-118423,2019-03-24,Dennis Pardue,Peoria,Furniture,FUR-BO-10000362,359.058,-35.9058,loss,-10.000000
1175,CA-2019-129217,2019-05-10,Dennis Pardue,Aurora,Office Supplies,OFF-AP-10002439,70.970,-191.6190,loss,-270.000000
1219,CA-2019-131884,2019-12-06,Dennis Kane,Marion,Furniture,FUR-CH-10004860,70.686,-24.2352,loss,-34.285714
1398,CA-2019-145065,2019-12-12,Dennis Kane,San Diego,Office Supplies,OFF-BI-10002437,24.448,8.8624,low profit,36.250000
1621,CA-2019-162950,2019-06-28,Dorothy Wardle,Troy,Furniture,FUR-BO-10001918,482.940,-376.6932,loss,-78.000000
2021,CA-2020-120530,2020-04-07,Dorris liebe,New York City,Furniture,FUR-CH-10000454,658.746,146.3880,medium profit,22.222222
2292,CA-2020-138478,2020-10-21,Dennis Pardue,North Las Vegas,Office Supplies,OFF-AR-10002240,113.220,29.4372,low profit,26.000000
2294,CA-2020-138583,2020-05-24,Dennis Pardue,Philadelphia,Office Supplies,OFF-AR-10001860,16.656,3.3312,low profit,20.000000
2447,CA-2020-148516,2020-08-07,Dorothy Wardle,Edmonds,Technology,TEC-AC-10003610,179.970,86.3856,low profit,48.000000
2735,CA-2020-165820,2020-09-26,Dorothy Wardle,San Francisco,Office Supplies,OFF-PA-10004735,12.960,6.2208,low profit,48.000000
3089,CA-2021-114552,2021-09-02,Dorris liebe,Cleveland,Furniture,FUR-FU-10002960,15.072,4.1448,low profit,27.500000
3278,CA-2021-123134,2021-05-02,Dorothy Wardle,Westfield,Furniture,FUR-FU-10003975,129.930,12.9930,low profit,10.000000
3441,CA-2021-131954,2021-01-21,Darrin Sayre,Seattle,Furniture,FUR-BO-10001619,84.980,18.6956,low profit,22.000000
3465,CA-2021-133046,2021-07-27,Dennis Kane,Seattle,Furniture,FUR-FU-10001940,23.880,10.5072,low profit,44.000000
3701,CA-2021-144848,2021-04-04,Darrin Sayre,New York City,Office Supplies,OFF-SU-10000646,240.370,7.2111,low profit,3.000000
3818,CA-2021-150931,2021-01-06,Dennis Pardue,Tuscaloosa,Office Supplies,OFF-BI-10004728,33.740,15.5204,low profit,46.000000
3887,CA-2021-154466,2021-01-01,Dennis Pardue,Franklin,Office Supplies,OFF-BI-10002012,3.600,1.7280,low profit,48.000000
4102,CA-2021-165099,2021-12-11,Dennis Kane,Abilene,Office Supplies,OFF-AP-10001634,1.392,-3.7584,loss,-270.000000
4127,CA-2021-166835,2021-11-12,Dennis Kane,Lancaster,Office Supplies,OFF-ST-10002574,221.024,-55.2560,loss,-25.000000
4535,US-2020-111290,2020-07-22,Dennis Kane,Westland,Office Supplies,OFF-AR-10001761,29.200,10.5120,low profit,36.000000
4616,US-2020-139087,2020-07-17,Dennis Kane,Seattle,Furniture,FUR-FU-10001847,12.420,4.4712,low profit,36.000000
4842,US-2021-125717,2021-09-28,Darrin Sayre,Aurora,Furniture,FUR-FU-10001979,32.776,3.2776,low profit,10.000000
4845,US-2021-126060,2021-04-14,Dorothy Wardle,Fayetteville,Furniture,FUR-BO-10003433,198.272,-32.2192,loss,-16.250000
4954,US-2021-155299,2021-06-08,Dorris liebe,Pasadena,Office Supplies,OFF-AP-10002203,1.624,-4.4660,loss,-275.000000
4986,US-2021-164147,2021-02-02,Dorothy Wardle,Columbus,Office Supplies,OFF-FA-10002780,21.456,6.9732,low profit,32.500000

In [38]:
# 10- create a new column order_year and populate it with year of order_date. ( hint : use the series objects slice method )
# option 1
#df['order_year'] = df['order_date'].str.slice(stop = 4)
#df

# option 2 
df['order_year'] = df['order_date'].str.slice(start=0, stop = 4)
df

,order_id,order_date,customer_name,city,category,product_id,sales,profit,profit_category,sales_profit_ratio,order_year
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113,medium profit,29.00,2018
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354,loss,-17.50,2018
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696,low profit,35.00,2018
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257,low profit,33.75,2018
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288,low profit,35.00,2018
...,...,...,...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696,low profit,32.50,2021
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896,low profit,47.00,2021
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812,low profit,47.00,2021
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640,low profit,29.00,2021
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492,loss,-52.00,2021

In [42]:
# 11 - delete column sales_profit_ratio from the dataframe
df.drop(columns = 'sales_profit_ratio', inplace=True)
df

,order_id,order_date,customer_name,city,category,product_id,sales,profit,profit_category,order_year
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113,medium profit,2018
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354,loss,2018
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696,low profit,2018
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257,low profit,2018
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288,low profit,2018
...,...,...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696,low profit,2021
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896,low profit,2021
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812,low profit,2021
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640,low profit,2021
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492,loss,2021

In [44]:
# 12- delete all the rows where profit is negative 
df.drop(index = df[df['profit'] < 0].index, inplace=True)
df

,order_id,order_date,customer_name,city,category,product_id,sales,profit,profit_category,order_year
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113,medium profit,2018
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696,low profit,2018
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257,low profit,2018
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288,low profit,2018
5,CA-2018-100391,2018-05-25,Barry Weirich,New York City,Office Supplies,OFF-PA-10001471,14.620,6.7252,low profit,2018
...,...,...,...,...,...,...,...,...,...,...
5002,US-2021-168613,2021-10-08,Gary McGarr,New York City,Furniture,FUR-CH-10002372,145.764,3.2392,low profit,2021
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696,low profit,2021
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896,low profit,2021
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812,low profit,2021
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640,low profit,2021